### ISSUE TITLE
NameUtils.java regex for valid entry names is too strict

### ISSUE THREAD

**Issue by DragonflyDoomworks** [MTrop/DoomStruct#11]
Within NameUtils.java the lump names regex appears to be too strict. It's possible for patches to use the plus character ( + ) in their name, but doing so causes it to throw an error due to invalid characters. A live example of a WAD with this naming can be seen in Otex v1.1 (https://www.doomworld.com/idgames/graphics/otex_1_1)

I'm unsure what other characters may be missing from the regex, if any.

https://github.com/MTrop/DoomStruct/blob/4ddae4d1a102f88e5af1e3f7243de7750614ee1b/src/main/java/net/mtrop/doom/util/NameUtils.java#L22

**Comment by derekmd** [comment]
Duplicate report of https://github.com/MTrop/DoomStruct/issues/8. I've at least submitted a PR for char `+` that's known to exist in the wild.

**Comment by MTrop** [comment]
@derekmd This is kinda the "Entry Flavor" of #8. 

I wish we had a more concrete outline of what should be allowed in entries and textures, but I'm not sure that Doom _itself_ has any idea, either (other than non-whitespace, ANSI characters with no lower-case letters). The "allowed" sets of characters seems to be consensus-driven, especially since it allows characters that aren't allowed in most filesystems.

I'll review the PR soon. It seems like a cautious approach to allowing characters is gonna be the correct one moving forward, since this sort of thing is limited to what tools allow, instead of what the engine does.
