### ISSUE TITLE
Need an option to change the Hardcoded Palette Translucent Index

### ISSUE THREAD

**Issue by Lemon-King** [MTrop/DoomStruct#17]
An option to change or disable the hardcoded palette translucent index of 255 would be useful.
Hexen has a few cases where 255 is not always translucent. Such as SKYFOG2, finale1 and finale2.

**Comment by MTrop** [comment]
This is true, however this is handled by game logic rather than data itself.

SKYFOG2 uses color 0 as the translucent color in-game, and is not translucent in game data (it appears as a solid color 0 pixel). The game knows to treat color 0 in a secondary sky layer as translucent.

FINALE1 and FINALE2 are not Doom patches (Pictures in DoomStruct), and are full-screen RAW pixels (Flat format). These graphics do not have translucent data.

Changing which pixel would be a translucent one would affect the data itself, and is not necessary for these situations.
